# Python Programming Essentials
![python.png]()

## Course Overview

Welcome to the Python Programming Essentials course.

## Key Highlights

- **Fundamental Programming Concepts:** Develop a solid understanding of essential programming principles and methodologies.
- **Data Science and Machine Learning Exploration:** Engage with practical applications on platforms such as Kaggle and Jupyter Notebooks, utilizing essential libraries for real-world data analysis and machine learning.
- **Coding Foundations:** Uncover the fundamentals of coding, spanning from high-level languages to low-level languages, and grasp the core building blocks of programming.

## Topics Explored

- **Object-Oriented Programming (OOP):** Delve into OOP principles, including the study of classes, inheritance, polymorphism, and composition.
- **Data Representation:** Understand the intricacies of representing data using integers, floating-point numbers, characters, strings, and more.
- **Control Flow and Logic Mastery:** Develop expertise in controlling program flow through conditional statements, loops, and logical operators.
- **File Handling Techniques:** Acquire skills in reading from and writing to files, managing different file types, and handling data effectively.

## Tools and Environments Explored

- **Integrated Development Environment (IDE) Exploration:** Discover the capabilities of popular IDEs such as Visual Studio Code, understanding their role in promoting efficient coding practices.
- **Python Package Management Exploration:** Explore PIP and Conda for seamless handling of package installation, version control, and virtual environments.
- **Version Control with Git:** Embrace collaborative coding practices using Git and GitHub, recognized as the industry-standard platform for version control and open-source collaboration.

## Contact Information

- **Email:** A.Asgharpoor1993@Gmail.com
- **Portfolio:** [ArmanAsq.GitHub.io](https://ArmanAsq.GitHub.io)
- **GitHub Profile:** [github.com/armanasq](https://github.com/armanasq)

![Capture.PNG]()

---

**1. Integer (int):**
   - Whole numbers without decimal points.
   - Examples: -3, 0, 42

**2. Floating-Point (float):**
   - Numbers with decimal points.
   - Examples: -3.14, 0.0, 3.14159

**3. Character (char):**
   - A single character, such as a letter, number, or symbol.
   - Examples: 'A', '7', '$'

**4. String (str):**
   - A sequence of characters.
   - Examples: "Hello, World!", "12345"

**5. Boolean (bool):**
   - A binary value, either true or false.
   - Examples: True, False

**6. List (list):**
   - An ordered collection of elements, which can be of different data types.
   - Examples: [1, 2, 3], ["apple", "banana", "cherry"]

**7. Tuple (tuple):**
   - Similar to a list but is immutable, meaning its elements cannot be changed after creation.
   - Examples: (1, 2, 3), ("red", "green", "blue")

**8. Dictionary (dict):**
   - A collection of key-value pairs.
   - Examples: {"name": "Alice", "age": 30}, {"city": "New York", "population": 8,400,000}

**9. Set (set):**
   - An unordered collection of unique elements.
   - Examples: {1, 2, 3}, {"apple", "banana", "cherry"}

**10. Null/None (NoneType):**
   - Represents the absence of a value.
   - Example: None

**11. Custom Data Types (e.g., Classes and Objects):**
   - User-defined data types like classes and objects.
   - Examples: class Person, object Car

In [ ]:
# Integer (int) data type
my_integer = 42
print(type(my_integer))

<class 'int'>

In [ ]:
# Floating-Point (float) data type
my_float = 3.14159
print(type(my_float))

<class 'float'>

In [ ]:
# Character (char) or Single-Character String (str) data type
my_char = 'A'
print(type(my_char))

<class 'str'>

In [ ]:
# String (str) data type
my_string = "Hello, World!"
print(type(my_string))

<class 'str'>

In [ ]:
# Boolean (bool) data type
my_boolean = True
print(type(my_boolean))

<class 'bool'>

In [ ]:
# List (list) data type
my_list = [1, 2, 3]
print(type(my_list))

<class 'list'>

In [ ]:
# Tuple (tuple) data type
my_tuple = (1, 2, 3)
print(type(my_tuple))

<class 'tuple'>

In [ ]:
# Dictionary (dict) data type
my_dict = {"name": "Alice", "age": 30}
print(type(my_dict))

<class 'dict'>

In [ ]:
# Set (set) data type
my_set = {1, 2, 3}
print(type(my_set))

<class 'set'>

In [ ]:
# None (NoneType) data type
my_none = None
print(type(my_none))

<class 'NoneType'>

In [ ]:
# Custom Data Type using Class
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

my_person = Person("Bob", 25)
print(type(my_person))

<class '__main__.Person'>

# Type Conversion

In [ ]:
# Implicit Type Conversion (Auto Type Conversion)
num_int = 123  # An integer
num_float = 1.23  # A float

result = num_int + num_float  # The float is implicitly converted to int for the addition

print("Result:", result)
print("Type of result:", type(result))

Result: 124.23
Type of result: <class 'float'>

In [ ]:
# Explicit Type Conversion (Type Casting)
num_str = "456"  # A string
num_int = int(num_str)  # Explicitly convert the string to an integer
num_float = float(num_str)  # Explicitly convert the string to a float

print("Integer:", num_int)
print("Float:", num_float)

Integer: 456
Float: 456.0

In [ ]:
# Type Conversion between Strings and Numbers
num_str = "123"
num_int = int(num_str)  # Convert string to integer
num_float = float(num_str)  # Convert string to float

print("Integer from string:", num_int)
print("Float from string:", num_float)

# Converting numbers to strings
num = 456
num_str = str(num)  # Convert integer to string

print("String from integer:", num_str)

Integer from string: 123
Float from string: 123.0
String from integer: 456

In [ ]:
# Type Conversion between Lists and Strings
my_list = [1, 2, 3]
list_str = str(my_list)  # Convert list to a string

print("String from list:", list_str)

# To convert the string back to a list, you can use eval() (caution: this can execute arbitrary code)
recovered_list = eval(list_str)
print("List from string:", recovered_list)

String from list: [1, 2, 3]
List from string: [1, 2, 3]

In [ ]:
# Type Conversion between Floating-Point and Integer
num_float = 3.14
num_int = int(num_float)  # Convert float to integer (truncates decimal part)

print("Integer from float:", num_int)

Integer from float: 3

In [ ]:
# Type Conversion with Built-in Functions
num_str = "123"
num_int = int(num_str)  # Using int() for type conversion
num_float = float(num_str)  # Using float() for type conversion
num_str_from_int = str(num_int)  # Using str() for type conversion

print("Integer from string:", num_int)
print("Float from string:", num_float)
print("String from integer:", num_str_from_int)

Integer from string: 123
Float from string: 123.0
String from integer: 123

# Variable Naming

Naming variables in programming is important for code clarity and functionality. There are certain rules and conventions for naming variables:

**Rules for Naming Variables:**

1. **Variable Names Must Start with a Letter or an Underscore (_):**
   - Variable names can begin with a letter (a to z, A to Z) or an underscore (_).
   - For example, `counter`, `_total`, `Name` are valid variable names.

2. **Variable Names Can Contain Letters, Digits, and Underscores:**
   - Variable names can contain letters (a to z, A to Z), digits (0 to 9), and underscores (_).
   - For example, `variable_1`, `count_2`, `first_name` are valid variable names.

3. **Variable Names Are Case-Sensitive:**
   - Variable names are case-sensitive in most programming languages. This means that `count` and `Count` are considered different variables.

4. **Do Not Use Reserved Words or Keywords:**
   - Avoid using reserved words or keywords that have special meanings in the programming language. For example, in Python, you should not use variable names like `if`, `while`, or `for`.

**Naming Conventions:**

While the rules above are fundamental, it's also important to follow naming conventions for better code readability and maintainability. Common naming conventions include:

1. **Use Descriptive Names:**
   - Choose variable names that are meaningful and describe the purpose of the variable. For example, use `total_score` instead of `ts` or `temp_value` instead of `x`.

2. **Use CamelCase or Snake_case:**
   - In some programming languages, variables are named using CamelCase (capitalizing the first letter of each word, e.g., `totalScore`) or Snake_case (words separated by underscores, e.g., `total_score`). Follow the convention used in your language.

3. **Avoid Single-Letter Variable Names (Except in Specific Cases):**
   - Single-letter variable names like `x`, `y`, or `i` should be avoided in most cases. They can be used in specific contexts like loop counters or mathematical formulas.

4. **Consistency:**
   - Be consistent with your variable naming throughout your code. If you use `user_age` in one part of your program, continue to use it elsewhere.

5. **Meaningful Prefixes (for Global/Class Variables):**
   - In some cases, you may use prefixes to indicate variable scope. For example, `g_total` for a global variable or `obj_name` for an object's property.

**Examples of Valid Variable Names:**

- `first_name`
- `totalScore`
- `_counter`
- `temp_value`
- `userAge`
- `MAX_VALUE`
- `counter1`

**Examples of Invalid Variable Names:**

- `1variable` (starts with a digit)
- `first name` (contains a space)
- `if` (a reserved keyword)
- `@total` (contains special characters)
- `my-variable` (contains a hyphen, not allowed)

Adhering to variable naming rules and conventions ensures that your code is more readable and easier to maintain, both for you and for others who may read your code.

# Comments and Documentation Strings

In [ ]:
# This is a single-line comment

In [ ]:
'''
This is a multi-line comment or docstring.
It can span multiple lines and is often used for documentation.
'''

'\nThis is a multi-line comment or docstring.\nIt can span multiple lines and is often used for documentation.\n'

# Indentation and Code Blocks

In [ ]:
var = 10
if var == 10:
    # Code inside the if block
    print('Var is 10')
else:
    # Code inside the else block
    print('Var is not 10')

Var is 10

# Arithmetic Operators

In [ ]:
a = 10
b = 3

# Addition
addition = a + b
print("Addition:", addition)

# Subtraction
subtraction = a - b
print("Subtraction:", subtraction)

# Multiplication
multiplication = a * b
print("Multiplication:", multiplication)

# Division
division = a / b
print("Division:", division)

# Modulus (remainder)
modulus = a % b
print("Modulus:", modulus)

# Exponentiation
exponentiation = a ** b
print("Exponentiation:", exponentiation)

# Floor Division (rounded down to the nearest integer)
floor_division = a // b
print("Floor Division:", floor_division)

# Unary Negation
negation = -a
print("Negation:", negation)

Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Modulus: 1
Exponentiation: 1000
Floor Division: 3
Negation: -10

# Comparison Operators

In [ ]:
a = 10
b = 3

# Equal
is_equal = a == b
print("Equal:", is_equal)

# Not Equal
is_not_equal = a != b
print("Not Equal:", is_not_equal)

# Greater Than
is_greater_than = a > b
print("Greater Than:", is_greater_than)

# Less Than
is_less_than = a < b
print("Less Than:", is_less_than)

# Greater Than or Equal To
is_greater_equal = a >= b
print("Greater Than or Equal To:", is_greater_equal)

# Less Than or Equal To
is_less_equal = a <= b
print("Less Than or Equal To:", is_less_equal)

Equal: False
Not Equal: True
Greater Than: True
Less Than: False
Greater Than or Equal To: True
Less Than or Equal To: False

# Logical Operators

In [ ]:
a = True
b = False

# AND
logical_and = a and b
print("Logical AND:", logical_and)

# OR
logical_or = a or b
print("Logical OR:", logical_or)

# NOT
logical_not_a = not a
logical_not_b = not b
print("Logical NOT for 'a':", logical_not_a)
print("Logical NOT for 'b':", logical_not_b)

Logical AND: False
Logical OR: True
Logical NOT for 'a': False
Logical NOT for 'b': True

# Input and Output

In [ ]:
# Displaying Output
print("Hello, World!")

Hello, World!

In [ ]:
# User Input
user_name = input("Enter your name: ")
print(f"Hello, {user_name}!")

Enter your name: Arman
Hello, Arman!

**Assignment Operators:**

Assignment operators are used to assign values to variables. They allow you to store data in variables for later use.

1. **Assignment (=):**
   - The most basic assignment operator.
   - It assigns the value on the right to the variable on the left.
   - Example: `x = 10` assigns the value 10 to the variable `x`.

2. **Addition Assignment (+=):**
   - Adds the value on the right to the current value of the variable on the left.
   - Example: `x += 5` is equivalent to `x = x + 5`.

3. **Subtraction Assignment (-=):**
   - Subtracts the value on the right from the current value of the variable on the left.
   - Example: `x -= 3` is equivalent to `x = x - 3`.

4. **Multiplication Assignment (*=):**
   - Multiplies the current value of the variable on the left by the value on the right.
   - Example: `x *= 2` is equivalent to `x = x * 2`.

5. **Division Assignment (/=):**
   - Divides the current value of the variable on the left by the value on the right.
   - Example: `x /= 4` is equivalent to `x = x / 4`.

6. **Modulus Assignment (%=):**
   - Calculates the remainder when the current value of the variable on the left is divided by the value on the right.
   - Example: `x %= 3` is equivalent to `x = x % 3`.

7. **Exponentiation Assignment (**=):**
   - Raises the current value of the variable on the left to the power of the value on the right.
   - Example: `x **= 2` is equivalent to `x = x ** 2`.

8. **Floor Division Assignment (//=):**
   - Performs floor division on the current value of the variable on the left and the value on the right.
   - Example: `x //= 3` is equivalent to `x = x // 3`.

In [ ]:
# Assignment
x = 10
print(x)

10

In [ ]:
# Addition Assignment
x = 5
x += 3  # Equivalent to x = x + 3
print(x)

8

In [ ]:
# Subtraction Assignment
x = 10
x -= 2  # Equivalent to x = x - 2
print(x)

8

In [ ]:
# Multiplication Assignment
x = 7
x *= 4  # Equivalent to x = x * 4
print(x)

28

In [ ]:
# Division Assignment
x = 20
x /= 5  # Equivalent to x = x / 5
print(x)

4.0

In [ ]:
# Modulus Assignment
x = 17
x %= 4  # Equivalent to x = x % 4
print(x)

1

In [ ]:
# Exponentiation Assignment
x = 3
x **= 2  # Equivalent to x = x ** 2
print(x)

9

In [ ]:
# Floor Division Assignment
x = 13
x //= 4  # Equivalent to x = x // 4
print(x)

3

# Order of Operations in Python (Operator Precedence)

In Python, operators have different levels of precedence, which determine the order in which they are evaluated in an expression. Understanding operator precedence is crucial for writing correct and predictable code. Here are the key rules for the order of operations:

1. **Parentheses:** Expressions within parentheses are evaluated first. You can use parentheses to override the default precedence.

2. **Exponentiation (`**`):** Exponentiation is evaluated before other mathematical operations. For example, `2 ** 3` calculates 2 to the power of 3.

3. **Multiplication (`*`), Division (`/`), Floor Division (`//`), and Modulus (`%`):** These operations are evaluated from left to right.

4. **Addition (`+`) and Subtraction (`-`):** Addition and subtraction are also evaluated from left to right.

5. **Comparison Operators:** Comparison operators, such as `<`, `>`, `<=`, `>=`, `==`, and `!=`, are evaluated after arithmetic operations. They return Boolean values (`True` or `False`).

6. **Logical Operators (`and`, `or`, `not`):** Logical operators are evaluated after comparison operators. `and` has higher precedence than `or`, and `not` has the highest precedence.

7. **Assignment Operators (`=`, `+=`, `-=`):** Assignment operators are evaluated last.

In [ ]:
result = (3 + 5) ** 2 / 2 + 4  # Parentheses first, then exponentiation, division, and addition
print(result)  # Output: 38.0

is_valid = (5 > 3) and (10 % 2 == 0)  # Comparison, modulus, and logical 'and'
print(is_valid)  # Output: True

36.0
True

In [ ]:
result = (((5 + 3) ** 2 / 2 + 4) > 10 and (not (15 % 3 == 0))) or (2 * (4 / 2) - 1)
print(result)

3.0

# Formatting Output

In [ ]:
# Using f-strings to format output
name = "Alice"
age = 30
print(f"My name is {name} and I am {age} years old.")

My name is Alice and I am 30 years old.

In [ ]:
# Using string concatenation to combine strings
greeting = "Hello, "
name = "Bob"
message = greeting + name
print(message)

Hello, Bob

In [ ]:
# Using string interpolation with the .format() method
product = "Laptop"
price = 1000
output = "The {} costs ${}".format(product, price)
print(output)

The Laptop costs $1000

In [ ]:
# Using string concatenation with the % operator
item = "Book"
quantity = 3
price = 10.99
output = "You purchased %d %s for a total of $%.2f." % (quantity, item, quantity * price)
print(output)

You purchased 3 Book for a total of $32.97.

# String Method

String Concatenation: Combining two or more strings.

In [ ]:
string1 = "Hello"
string2 = "World"
result = string1 + " " + string2
print(result)

Hello World

String Length

In [ ]:
print(len(result))

11

String Slicing

In [ ]:
text = "Python is fun"
substring = text[7:9]  # Slicing from index 7 to 9 (exclusive)
print(substring)

is

String Splitting

In [ ]:
sentence = "This is a sentence."
words = sentence.split(" ")
print(words)

['This', 'is', 'a', 'sentence.']

String Joining

In [ ]:
words = ['This', 'is', 'a', 'sentence.']
sentence = " ".join(words)
print(sentence)

This is a sentence.

String Replacement

In [ ]:
text = "I like cats."
new_text = text.replace("cats", "dogs")
print(new_text)

I like dogs.

String Conversion

In [ ]:
text = "Hello, World!"
uppercase = text.upper()
lowercase = text.lower()
print(uppercase)
print(lowercase)

HELLO, WORLD!
hello, world!

String Stripping

In [ ]:
text = "   Some text with spaces   "
stripped_text = text.strip()
print(stripped_text)

Some text with spaces

String Searching

In [ ]:
text = "Python is fun"
index = text.find("is")
print(index)

7

Formatting Output

In [ ]:
name = "Alice"
age = 30
print(f"My name is {name} and I am {age} years old.")

My name is Alice and I am 30 years old.

 String Concatenation

In [ ]:
greeting = "Hello, " + name + "!"
print(greeting)

Hello, Alice!

String Interpolation

In [ ]:
formatted_string = "Name: {}, Age: {}".format(name, age)
print(formatted_string)

Name: Alice, Age: 30

# Control Flow and Logic

Control flow in programming determines the order in which statements are executed. It helps make decisions, repeat actions, and manage the flow of your program. Key control flow concepts include:

1. **Conditional Statements (if, elif, else):**
   - Conditional statements allow you to make decisions in your code based on conditions.
   - The `if` statement is used to check a condition. If the condition is true, the code block inside the `if` is executed.
   - The `elif` (else if) statement is used to check additional conditions after the initial `if`.
   - The `else` statement is used to specify what to do if none of the previous conditions are met.

2. **Loops (for and while):**
   - Loops allow you to repeat a block of code multiple times.
   - The `for` loop is used to iterate over a sequence (e.g., a list or range).
   - The `while` loop is used to repeat a block of code as long as a condition is true.

3. **Break and Continue Statements:**
   - The `break` statement is used to exit a loop prematurely when a certain condition is met.
   - The `continue` statement is used to skip the current iteration and move to the next one in a loop.

4. **Logical Operators (and, or, not):**
   - Logical operators are used to combine and manipulate conditions in conditional statements.
   - `and` - Logical AND, returns true if both conditions are true.
   - `or` - Logical OR, returns true if at least one condition is true.
   - `not` - Logical NOT, returns the opposite of the condition.

5. **Comparison Operators:**
   - Comparison operators are used to compare values.
   - `==` - Equal, returns true if both values are equal.
   - `!=` - Not Equal, returns true if values are not equal.
   - `>` - Greater Than, returns true if the left value is greater.
   - `<` - Less Than, returns true if the left value is less.
   - `>=` - Greater Than or Equal To, returns true if the left value is greater or equal.
   - `<=` - Less Than or Equal To, returns true if the left value is less or equal.

In [ ]:
# Conditional Statements
score = 75

if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
else:
    print("D")

C

In [ ]:
# Loops
# Using a for loop to iterate over a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# Using a while loop to count from 1 to 5
count = 1
while count <= 5:
    print(count)
    count += 1

apple
banana
cherry
1
2
3
4
5

In [ ]:
# Break and Continue Statements
# Using break to exit a loop prematurely
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
for number in numbers:
    if number == 5:
        break
    print(number)

# Using continue to skip even numbers
for number in numbers:
    if number % 2 == 0:
        continue
    print(number)

1
2
3
4
1
3
5
7
9

In [ ]:
# Logical Operators
# Using logical operators to combine conditions
age = 25
income = 50000

if age >= 18 and income > 30000:
    print("You qualify for the program.")

if age < 18 or income < 30000:
    print("You do not qualify for the program.")

if not (age < 18 and income > 30000):
    print("You do not qualify for the program.")

You qualify for the program.
You do not qualify for the program.

In [ ]:
# Comparison Operators
# Using comparison operators to compare values
x = 10
y = 20

if x == y:
    print("x is equal to y")
if x != y:
    print("x is not equal to y")
if x < y:
    print("x is less than y")
if x > y:
    print("x is greater than y")
if x <= y:
    print("x is less than or equal to y")
if x >= y:
    print("x is greater than or equal to y")

x is not equal to y
x is less than y
x is less than or equal to y

# Data Structures in Python

## Introduction

Data structures are fundamental components in programming that allow efficient organization and manipulation of data. Python provides several built-in data structures that suit different use cases. In this guide, we will explore various data structures in Python.

## Table of Contents

1. [Lists](#lists)
2. [Tuples](#tuples)
3. [Sets](#sets)
4. [Dictionaries](#dictionaries)
5. [Strings](#strings)
6. [Stacks](#stacks)
7. [Queues](#queues)
8. [Linked Lists](#linked-lists)
9. [Trees](#trees)
10. [Graphs](#graphs)

## Lists

A list is an ordered collection of elements that can be of different data types.

```python
# Creating a list
my_list = [1, 2, 3, 'hello', True]

# Accessing elements
print(my_list[0])  # Output: 1

# Modifying elements
my_list[1] = 4

# Adding elements
my_list.append(5)

# Removing elements
my_list.remove('hello')
```

## Tuples

A tuple is similar to a list but is immutable, meaning its elements cannot be changed after creation.

```python
# Creating a tuple
my_tuple = (1, 2, 3, 'world', False)

# Accessing elements
print(my_tuple[0])  # Output: 1
```

## Sets

A set is an unordered collection of unique elements.

```python
# Creating a set
my_set = {1, 2, 3, 3, 4, 5}

# Adding elements
my_set.add(6)

# Removing elements
my_set.remove(3)
```

## Dictionaries

A dictionary is a collection of key-value pairs.

```python
# Creating a dictionary
my_dict = {'name': 'John', 'age': 25, 'city': 'New York'}

# Accessing elements
print(my_dict['name'])  # Output: John

# Modifying elements
my_dict['age'] = 26

# Adding elements
my_dict['gender'] = 'Male'
```

## Strings

While not a traditional data structure, strings are crucial for storing and manipulating text.

```python
# Creating a string
my_string = 'Python is powerful'

# Concatenation
new_string = my_string + ' and versatile'

# Slicing
substring = my_string[7:13]  # Output: 'is pow'
```

## Stacks

A stack is a Last In, First Out (LIFO) data structure.

```python
# Using a list as a stack
stack = [1, 2, 3]

# Pushing an element
stack.append(4)

# Popping an element
popped_element = stack.pop()
```

## Queues

A queue is a First In, First Out (FIFO) data structure.

```python
# Using collections.deque as a queue
from collections import deque

queue = deque([1, 2, 3])

# Enqueuing an element
queue.append(4)

# Dequeuing an element
dequeued_element = queue.popleft()
```

## Linked Lists

A linked list is a linear collection of elements where each element points to the next one.

```python
# Node class for a singly linked list
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

# Creating a linked list
head = Node(1)
head.next = Node(2)
head.next.next = Node(3)
```

## Trees

A tree is a hierarchical data structure with a root element and subtrees.

```python
# Node class for a binary tree
class TreeNode:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

# Creating a binary tree
root = TreeNode(1)
root.left = TreeNode(2)
root.right = TreeNode(3)
```

## Graphs

A graph is a collection of nodes connected by edges.

```python
# Using a dictionary to represent a graph
my_graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D'],
    'C': ['A', 'E'],
    'D': ['B'],
    'E': ['C']
}
```

In [ ]:
# Lists
my_list = [1, 2, 3, 4, 5]
my_list.append(6)  # Adding an element
my_list.remove(3)  # Removing an element
print(my_list)

[1, 2, 4, 5, 6]

In [ ]:
list_of_random_things = [1, 3.4, 'a string', True]
list_of_random_things[0]

1

In [ ]:
list_of_random_things[len(list_of_random_things) - 1]

True

In [ ]:
list_of_random_things[1:2]

[3.4]

In [ ]:
 5 not in list_of_random_things

True

In [ ]:
 5 in list_of_random_things

False

In [ ]:
# Tuples
my_tuple = (1, 2, 3)
# Cannot modify the tuple, it's immutable
my_tuple

(1, 2, 3)

In [ ]:
# Dictionaries
my_dict = {"name": "Alice", "age": 30}
print(my_dict["name"])  # Accessing values by key
my_dict["city"] = "New York"  # Adding a new key-value pair
print(my_dict)

Alice
{'name': 'Alice', 'age': 30, 'city': 'New York'}

In [ ]:
# Sets
my_set = {1, 2, 3, 4, 5}
my_set.add(6)  # Adding an element
my_set.remove(3)  # Removing an element
print(my_set)

{1, 2, 4, 5, 6}

---

In [9]:
# List Example
my_list = [1, 2, 3, 'hello', True]
print("List Example:")
print("Original List:", my_list)
print("Accessing Element:", my_list[0])
my_list[1] = 4
print("Modified List:", my_list)
my_list.append(5)
print("List After Append:", my_list)
my_list.remove('hello')
print("List After Removal:", my_list)
print()

List Example:
Original List: [1, 2, 3, 'hello', True]
Accessing Element: 1
Modified List: [1, 4, 3, 'hello', True]
List After Append: [1, 4, 3, 'hello', True, 5]
List After Removal: [1, 4, 3, True, 5]

In [10]:
# Tuple Example
my_tuple = (1, 2, 3, 'world', False)
print("Tuple Example:")
print("Original Tuple:", my_tuple)
print("Accessing Element:", my_tuple[0])
print()

Tuple Example:
Original Tuple: (1, 2, 3, 'world', False)
Accessing Element: 1

In [11]:
# Set Example
my_set = {1, 2, 3, 3, 4, 5}
print("Set Example:")
print("Original Set:", my_set)
my_set.add(6)
print("Set After Addition:", my_set)
my_set.remove(3)
print("Set After Removal:", my_set)
print()

Set Example:
Original Set: {1, 2, 3, 4, 5}
Set After Addition: {1, 2, 3, 4, 5, 6}
Set After Removal: {1, 2, 4, 5, 6}

In [12]:
# Dictionary Example
my_dict = {'name': 'John', 'age': 25, 'city': 'New York'}
print("Dictionary Example:")
print("Original Dictionary:", my_dict)
print("Accessing Element:", my_dict['name'])
my_dict['age'] = 26
print("Modified Dictionary:", my_dict)
my_dict['gender'] = 'Male'
print("Dictionary After Addition:", my_dict)
print()

Dictionary Example:
Original Dictionary: {'name': 'John', 'age': 25, 'city': 'New York'}
Accessing Element: John
Modified Dictionary: {'name': 'John', 'age': 26, 'city': 'New York'}
Dictionary After Addition: {'name': 'John', 'age': 26, 'city': 'New York', 'gender': 'Male'}

In [13]:
# String Example
my_string = 'Python is powerful'
print("String Example:")
print("Original String:", my_string)
new_string = my_string + ' and versatile'
print("Concatenated String:", new_string)
substring = my_string[7:13]
print("Substring:", substring)
print()

String Example:
Original String: Python is powerful
Concatenated String: Python is powerful and versatile
Substring: is pow

In [14]:
# Stack Example
stack = [1, 2, 3]
print("Stack Example:")
print("Original Stack:", stack)
stack.append(4)
print("Stack After Push:", stack)
popped_element = stack.pop()
print("Popped Element:", popped_element)
print()

Stack Example:
Original Stack: [1, 2, 3]
Stack After Push: [1, 2, 3, 4]
Popped Element: 4

In [15]:
# Queue Example
from collections import deque
queue = deque([1, 2, 3])
print("Queue Example:")
print("Original Queue:", queue)
queue.append(4)
print("Queue After Enqueue:", queue)
dequeued_element = queue.popleft()
print("Dequeued Element:", dequeued_element)
print()

Queue Example:
Original Queue: deque([1, 2, 3])
Queue After Enqueue: deque([1, 2, 3, 4])
Dequeued Element: 1

In [16]:
# Linked List Example
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

print("Linked List Example:")
head = Node(1)
head.next = Node(2)
head.next.next = Node(3)
print("Linked List Elements:", head.data, head.next.data, head.next.next.data)
print()

Linked List Example:
Linked List Elements: 1 2 3

In [17]:
# Tree Example
class TreeNode:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

print("Tree Example:")
root = TreeNode(1)
root.left = TreeNode(2)
root.right = TreeNode(3)
print("Tree Elements:", root.data, root.left.data, root.right.data)
print()

Tree Example:
Tree Elements: 1 2 3

In [18]:
# Graph Example
print("Graph Example:")
my_graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D'],
    'C': ['A', 'E'],
    'D': ['B'],
    'E': ['C']
}
print("Graph Representation:", my_graph)
print()

Graph Example:
Graph Representation: {'A': ['B', 'C'], 'B': ['A', 'D'], 'C': ['A', 'E'], 'D': ['B'], 'E': ['C']}

# Mutability and Order in Data Structures

*Mutability:

Mutability refers to whether a data structure can be modified after its creation. In Python, data structures fall into two categories:

1. **Mutable Data Structures:**
   - Data structures like lists, dictionaries, and sets are mutable.
   - You can change their contents, add, remove, or update elements.

2. **Immutable Data Structures:**
   - Data structures like strings, tuples, and frozensets are immutable.
   - You cannot change their contents after creation.

**Order:**

Order refers to whether the data structure maintains the order of elements. In Python, data structures can be:

1. **Ordered Data Structures:**
   - Ordered data structures like lists and tuples maintain the order of elements. The order in which elements are added is preserved.

2. **Unordered Data Structures:**
   - Unordered data structures like dictionaries and sets do not guarantee a specific order for elements. The order may not match the order of insertion.

In [ ]:
# Lists are mutable and ordered
my_list = [1, 2, 3]
my_list[0] = 4  # Modifying an element
my_list.append(5)  # Adding an element
print("Mutable and Ordered List:", my_list)

# Strings are immutable and ordered
my_string = "Hello"
# my_string[0] = 'J'  # This will result in an error (immutable)
print("Immutable and Ordered String:", my_string)

# Dictionaries are mutable but not ordered (in Python 3.7+)
my_dict = {"name": "Alice", "age": 30}
my_dict["city"] = "New York"  # Adding a new key-value pair
# Dictionaries do not guarantee order in Python 3.7+
print("Mutable but Unordered Dictionary:", my_dict)

# Sets are mutable but not ordered
my_set = {3, 1, 2}
my_set.add(4)  # Adding an element
# Sets do not guarantee order
print("Mutable but Unordered Set:", my_set)

Mutable and Ordered List: [4, 2, 3, 5]
Immutable and Ordered String: Hello
Mutable but Unordered Dictionary: {'name': 'Alice', 'age': 30, 'city': 'New York'}
Mutable but Unordered Set: {1, 2, 3, 4}

# Iterable

An iterable is a fundamental concept in programming that refers to any object capable of returning its elements one at a time. In simpler terms, it is something you can loop over or iterate through. Iterables are commonly used in loops to process each element one by one.

Key characteristics of iterables include:

1. **Sequenced:** Iterables represent a sequence of elements.
2. **Access by Index:** Elements within an iterable can typically be accessed by their index or position in the sequence.
3. **Iteration:** You can use a loop or iterator to access each element of the iterable sequentially.

Common types of iterables in Python include:

1. **Lists:** Lists are sequences of items, and you can iterate through each item using a `for` loop.

2. **Strings:** Strings are sequences of characters, and you can loop through each character in the string.

3. **Tuples:** Tuples are sequences like lists but are immutable, meaning their elements cannot be changed after creation.

4. **Dictionaries:** You can iterate over keys, values, or key-value pairs in dictionaries.

5. **Sets:** Sets are collections of unique items, and you can loop through each unique item.

6. **Generators:** Generators are a way to create iterables on the fly using functions or expressions.

In [ ]:
# Lists are iterables
my_list = [1, 2, 3, 4, 5]
for item in my_list:
    print(item)

1
2
3
4
5

In [ ]:
# Strings are iterables
my_string = "Hello"
for char in my_string:
    print(char)

H
e
l
l
o

In [ ]:
# Tuples are iterables
my_tuple = (1, 2, 3, 4, 5)
for item in my_tuple:
    print(item)

1
2
3
4
5

In [ ]:
# Dictionaries are iterables (iterating over keys)
my_dict = {"name": "Alice", "age": 30}
for key in my_dict:
    print(key, my_dict[key])

name Alice
age 30

In [ ]:
# Sets are iterables
my_set = {3, 1, 2}
for item in my_set:
    print(item)

1
2
3

# Zip and Enumerate

**1. Zip:**

`zip` is a built-in Python function that is used for combining multiple iterables (e.g., lists, tuples) element-wise into a single iterable. It creates pairs of elements from corresponding positions in the input iterables.

The `zip` function takes two or more iterables as arguments and returns an iterator that generates tuples containing elements from the input iterables. If the input iterables are of unequal length, `zip` stops creating tuples when the shortest input iterable is exhausted.

In [ ]:
names = ["Alice", "Bob", "Charlie"]
scores = [95, 88, 75]

zipped = zip(names, scores)

for name, score in zipped:
    print(f"{name}: {score}")

Alice: 95
Bob: 88
Charlie: 75

In this example, the `zip` function combines the `names` and `scores` lists into pairs, which are then iterated through in a `for` loop.

**2. Enumerate:**

`enumerate` is another built-in Python function used to iterate through elements of an iterable (e.g., a list or string) along with their indices (positions). It returns tuples with the index and the corresponding element.

The `enumerate` function takes an iterable as its argument and returns an iterator that generates tuples with two values: the index and the element.

In [ ]:
fruits = ["apple", "banana", "cherry"]

for index, fruit in enumerate(fruits):
    print(f"Index {index}: {fruit}")

Index 0: apple
Index 1: banana
Index 2: cherry

In this example, the `enumerate` function is used to iterate through the `fruits` list and provides the index along with each fruit.

Both `zip` and `enumerate` are useful for combining and iterating through data in a structured way. They simplify tasks like iterating over multiple lists in parallel or tracking the position of elements in an iterable.

# List Comprehensions

List comprehensions in Python are a concise and readable way to create lists. They provide a compact and efficient way to generate lists by applying an expression to each item in an iterable (such as a list, tuple, or range) and filtering the items based on a condition. List comprehensions are often used to replace traditional `for` loops when creating and filtering lists. Here's the basic syntax for list comprehensions:

```python
new_list = [expression for item in iterable if condition]
```

- `expression` is the operation or value you want to include in the new list.
- `item` is a variable that represents each item in the iterable.
- `iterable` is the source data you're iterating over.
- `condition` (optional) is used to filter the items based on a specific condition.

In [ ]:
# Creating a list of squared numbers from 0 to 4
squared_numbers = [x**2 for x in range(5)]
print(squared_numbers)

[0, 1, 4, 9, 16]

In [ ]:
# Creating a list of even numbers from 0 to 9
even_numbers = [x for x in range(10) if x % 2 == 0]
print(even_numbers)

[0, 2, 4, 6, 8]

In [ ]:
# Creating a list of names with more than 5 characters
names = ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"]
long_names = [name for name in names if len(name) > 5]
print(long_names)

['Charlie']

List comprehensions can make your code more concise and easier to read. They are commonly used for tasks like filtering, transforming, and extracting data from iterable objects. However, it's essential to use them appropriately and avoid making them overly complex, as readability is important in Python code.

In [ ]:
import time

start_time = time.time()
squared_numbers = [x**2 for x in range(5)]
end_time = time.time()

print("Using List Comprehension:")
print(squared_numbers)
print("Time taken:", end_time - start_time, "seconds")

Using List Comprehension:
[0, 1, 4, 9, 16]
Time taken: 0.00011038780212402344 seconds

In [ ]:
import time

start_time = time.time()
squared_numbers = []
for x in range(5):
    squared_numbers.append(x**2)
end_time = time.time()

print("Using Traditional for Loop:")
print(squared_numbers)
print("Time taken:", end_time - start_time, "seconds")

Using Traditional for Loop:
[0, 1, 4, 9, 16]
Time taken: 7.510185241699219e-05 seconds

In [ ]:
import time

start_time = time.time()
even_numbers = [x for x in range(10) if x % 2 == 0]
end_time = time.time()

print("Using List Comprehension:")
print(even_numbers)
print("Time taken:", end_time - start_time, "seconds")

Using List Comprehension:
[0, 2, 4, 6, 8]
Time taken: 6.628036499023438e-05 seconds

In [ ]:
import time

start_time = time.time()
even_numbers = []
for x in range(10):
    if x % 2 == 0:
        even_numbers.append(x)
end_time = time.time()

print("Using Traditional for Loop:")
print(even_numbers)
print("Time taken:", end_time - start_time, "seconds")

Using Traditional for Loop:
[0, 2, 4, 6, 8]
Time taken: 0.00012445449829101562 seconds

In [ ]:
import time

names = ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"]

start_time = time.time()
long_names = [name for name in names if len(name) > 5]
end_time = time.time()

print("Using List Comprehension:")
print(long_names)
print("Time taken:", end_time - start_time, "seconds")

Using List Comprehension:
['Charlie']
Time taken: 0.00012969970703125 seconds

In [ ]:
import time

names = ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"]

start_time = time.time()
long_names = []
for name in names:
    if len(name) > 5:
        long_names.append(name)
end_time = time.time()

print("Using Traditional for Loop:")
print(long_names)
print("Time taken:", end_time - start_time, "seconds")

Using Traditional for Loop:
['Charlie']
Time taken: 8.893013000488281e-05 seconds

In [ ]:
import time
last_num = 100000000
start_time = time.time()
squared_numbers = [x**2 for x in range(last_num)]
end_time = time.time()

print("Using List Comprehension:")
print("Time taken:", end_time - start_time, "seconds")


start_time = time.time()
squared_numbers = []
for x in range(last_num):
    squared_numbers.append(x**2)
end_time = time.time()

print("Using Traditional for Loop:")
print("Time taken:", end_time - start_time, "seconds")

Using List Comprehension:
Time taken: 24.440292596817017 seconds
Using Traditional for Loop:
Time taken: 30.433871269226074 seconds

# Function
Certainly! Here's a comprehensive overview of functions in Python, including key concepts, definitions, and examples, presented in a slide-like format.

---
 Defining Functions

- A function is a reusable block of code.
- It's defined using the `def` keyword.

---

Parameters and Arguments

- Parameters are placeholders in a function definition.
- Arguments are the actual values passed to a function when it's called.

---

Return Values

- Functions can return values using the `return` statement.


---

Scope and Namespaces

- Variables have scope, which determines where they can be accessed.
- Local variables are within a function's scope.
- Global variables are accessible from anywhere in the code.

---

Lambda Functions

- Lambda functions are small, anonymous functions defined with `lambda`.
- They are often used for short, simple operations.

---

Variable-Length Arguments

- You can use `*args` and `**kwargs` to accept a variable number of positional and keyword arguments.

---

Nested Functions

- Functions can be defined inside other functions (nested functions).
---

Documentation (Docstrings)

- It's good practice to include docstrings to describe a function's purpose, parameters, and return values.

In [ ]:
def greet(name):
    print(f"Hello, {name}!")
name = input()
greet(name)

Arman
Hello, Arman!

In [ ]:
def add(a, b):  # a and b are parameters
    result = a + b
    return result

sum = add(3, 5)  # 3 and 5 are arguments
print(sum)

8

In [ ]:
def square(x):
    return x * x

result = square(4)  # Returns 16
print(result)

16

In [ ]:
x = 10  # Global variable

def example():
    y = 5  # Local variable

example()

print(x)  # Accessible
print(y)  # Raises an error (out of scope)

10

NameError: ignored

In [ ]:
double = lambda x: x * 2
result = double(5)  # Returns 10
print(result)

10

In [ ]:
def add(*args):
    result = 0
    for num in args:
        result += num
    return result

sum = add(2, 3, 5)  # Sum is 10

print(sum)

10

In [ ]:
def display_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

# Using **kwargs to pass additional information
display_info(name="Alice", age=30, country="USA", occupation="Engineer")

name: Alice
age: 30
country: USA
occupation: Engineer

In [ ]:
def outer_function(x):
    def inner_function(y):
        return x + y
    return inner_function

add_five = outer_function(5)
result = add_five(3)  # Returns 8
print(result)

8

In [ ]:
def multiply(a, b):
    """
    Multiply two numbers.

    Args:
        a (int): The first number.
        b (int): The second number.

    Returns:
        int: The result of the multiplication.
    """
    return a * b

# Modules

**What is a Module?**

In Python, a module is a file containing Python code. It can define functions, classes, and variables. Modules are used to organize code into reusable and manageable components. You can use modules to encapsulate and abstract functionality, making your code more readable and maintainable.

**Why Use Modules?**

- **Reusability:** Modules allow you to reuse code across multiple parts of your program or in different programs.
- **Organization:** Code can be organized into separate modules based on their functionality.
- **Abstraction:** Modules hide implementation details and provide a clean interface for other parts of the program to use.

**Importing Modules**

You can import modules using the `import` statement. For example:

```python
import math
```

This imports the `math` module, which provides mathematical functions and constants.

**Using Functions and Variables from Modules**

You can access functions and variables from a module using dot notation:

```python
import math

result = math.sqrt(16)  # Using the sqrt function from the math module
```

**Creating Your Own Modules**

To create your own module, you simply write a Python script with your functions, classes, or variables. You can then import this module into other parts of your program.

In [20]:
!touch my_script.py

In [21]:
!ls

my_script.py  sample_data

Define a function as sum:
```python
def sum(a, b):
  return a + b
```

In [22]:
from my_script import sum
print(sum(1,2))

3

In [23]:
import my_script
result = my_script.sum(1,2)
print(result)

3

# File Handling

File handling is a crucial aspect of programming. It involves operations such as reading, writing, creating, updating, and deleting files on your computer. In Python, you can perform these operations with built-in functions and modules.

## Types of Files

There are two main types of files: text files and binary files. Text files contain human-readable text, while binary files contain non-textual data like images or videos.

## Opening a File

To interact with a file, you must open it using the `open()` function. You specify the file's path and the mode (e.g., read, write, append).

```python
# Opening a text file for reading
file = open('example.txt', 'r')
```

## Closing a File

Always close a file after using it to free up system resources. You can use the `close()` method or the `with` statement for safe file handling.

```python
file.close()  # Closing the file
```

## Reading from a File

You can read the contents of a file using methods like `read()`, `readline()`, or `readlines()`.

```python
content = file.read()  # Read the entire file
```

## Writing to a File

To write to a file, open it in write mode ('w') or append mode ('a').

```python
# Opening a text file for writing
file = open('example.txt', 'w')
file.write('Hello, World!')
file.close()
```

## Working with Binary Files

Binary files require a different mode, like 'rb' for reading or 'wb' for writing. They are used for non-text data like images and videos.

```python
# Opening a binary file for reading
image = open('my_image.jpg', 'rb')
```

## Using the 'with' Statement

The `with` statement ensures proper file handling. It automatically closes the file when you're done.

```python
with open('example.txt', 'r') as file:
    content = file.read()
```

## Exception Handling

When working with files, handle exceptions to address potential errors, such as a file not found.

```python
try:
    file = open('non_existent_file.txt', 'r')
except FileNotFoundError:
    print('File not found.')
```

## File Operations

Python provides various operations for file manipulation, such as renaming, deleting, and checking file existence.

```python
import os

os.rename('old_file.txt', 'new_file.txt')  # Rename a file
os.remove('file_to_delete.txt')  # Delete a file
os.path.exists('file.txt')  # Check if a file exists
```

In [ ]:
# Opening a text file for writing
with open('example.txt', 'w') as file:
    file.write('Hello, World!')

# Opening a text file for reading
with open('example.txt', 'r') as file:
    content = file.read()

print(content)  # Output: 'Hello, World!'

# Copying a file
import shutil
shutil.copy('example.txt', 'example_copy.txt')

# Renaming a file
import os
os.rename('example_copy.txt', 'renamed_example.txt')

# Checking if a file exists
if os.path.exists('renamed_example.txt'):
    print('File exists.')

# Deleting a file
os.remove('renamed_example.txt')

# Object-Oriented Programming (OOP) in Python

Object-Oriented Programming is a paradigm that focuses on modeling real-world concepts using objects, which are instances of classes. OOP promotes encapsulation, abstraction, inheritance, and polymorphism to create modular, maintainable, and extensible code.

## Key Concepts

- **Class:** A blueprint for creating objects.
- **Object:** An instance of a class.
- **Attributes:** Characteristics of an object.
- **Methods:** Actions an object can perform.

## Encapsulation

- **Encapsulation:** The bundling of data (attributes) and methods that operate on the data into a single unit (an object).

## Abstraction

- **Abstraction:** Representing complex reality while hiding unnecessary details.
- Classes provide a level of abstraction.

## Inheritance

- **Inheritance:** Creating a new class based on an existing class (base or parent class). The new class inherits attributes and methods.

## Polymorphism

- **Polymorphism:** Objects of different classes can be treated as objects of a common superclass, promoting flexibility and extensibility.

## Composition

- **Composition:** Building complex objects by combining simpler objects. Promotes code reusability.

## Classes vs. Objects

- **Class:** The template for creating objects.
- **Object:** An instance of a class.

In the following code examples, we'll explore these OOP concepts and their practical applications.

In [ ]:
# Define a class
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def introduce(self):
        return f"My name is {self.name} and I am {self.age} years old."

# Create objects
person1 = Person("Alice", 30)
person2 = Person("Bob", 25)

# Access attributes and call methods
print(person1.name)  # Access attribute
print(person2.introduce())  # Call method

# Inheritance
class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)
        self.student_id = student_id

student = Student("Charlie", 21, "S12345")
print(student.introduce())  # Inherited method

# Polymorphism
people = [person1, person2, student]
for person in people:
    print(person.introduce())  # Polymorphic method call

In a function, a method and an attribute are specific concepts related to objects and object-oriented programming. Let's clarify these terms:

1. **Function:**
   - A function is a block of code that performs a specific task when called. It is a standalone piece of code that can accept inputs (parameters), perform operations, and produce outputs (return values).

2. **Method:**
   - A method is a function that is associated with an object or a class. Methods are functions that can be called on objects of a particular class. They typically operate on the data within the object and can modify its state.

3. **Attribute:**
   - An attribute is a variable associated with an object or a class. Attributes store information about the object's state. Unlike methods, attributes do not perform operations but hold data.

Here's an example to illustrate the difference between methods and attributes:

In [ ]:
class Dog:
    def __init__(self, name, age):
        self.name = name  # 'name' is an attribute
        self.age = age    # 'age' is an attribute

    def bark(self):
        print(f"{self.name} barks!")  # 'bark' is a method

# Creating an instance of the 'Dog' class
my_dog = Dog("Fido", 3)

# Accessing attributes
print(f"My dog's name is {my_dog.name}.")  # Accessing 'name' attribute
print(f"My dog is {my_dog.age} years old.")  # Accessing 'age' attribute

# Calling a method
my_dog.bark()  # Calling the 'bark' method

In the example above:

- `name` and `age` are attributes of the `Dog` class.
- `bark` is a method of the `Dog` class.
- You can access attributes directly using dot notation (e.g., `my_dog.name`) and call methods using parentheses (e.g., `my_dog.bark()`).

Attributes store data about the object, and methods perform actions on the object. Both attributes and methods are used to define the behavior and characteristics of objects in object-oriented programming.

# Class

## Creating Classes in Python

In Python, classes are the foundation of object-oriented programming. A class is a blueprint for creating objects, and objects are instances of classes. Understanding how to define and use classes is fundamental to building structured, modular, and maintainable code.

## Key Components

- **Attributes:** Characteristics or data stored within an object.
- **Methods:** Functions that define an object's behavior.
- **Constructor:** A special method (`__init__`) for initializing object attributes.

## Defining a Class

To define a class, use the `class` keyword, followed by the class name and a colon:

```python
class MyClass:
    pass
```

## Attributes

Attributes are used to store data within an object. They are defined within the class using the `self` keyword:

```python
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
```

## Methods

Methods are functions that define the behavior of the class:

```python
class Dog:
    def bark(self):
        print("Woof!")
```

## The Constructor (`__init__`)

The constructor is a special method that initializes object attributes. It is defined using the `__init__` method:

```python
class Car:
    def __init__(self, make, model):
        self.make = make
        self.model = model
```

## Class and Object

A class is like a blueprint, while an object is an instance created from the blueprint. Multiple objects can be created from a single class:

```python
my_car = Car("Toyota", "Camry")
```

In the following code examples, we'll explore these concepts and create practical classes.

In [ ]:
# Define a class
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} (a {self.breed} dog) barks!")

# Create objects
dog1 = Dog("Buddy", "Labrador")
dog2 = Dog("Lucy", "Bulldog")

# Access attributes and call methods
print(dog1.name)  # Access attribute
dog2.bark()  # Call method

# Create another class
class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 * self.radius * self.radius

# Create a circle object
circle = Circle(5)
print(f"Circle area: {circle.area()}")

In this example, we define two classes, `Dog` and `Circle`, create objects from them, and showcase attributes, methods, and constructors. Classes provide structure and organization to your code, making it more understandable and maintainable.

# Inheritance in Python

Inheritance is a fundamental concept in object-oriented programming (OOP) that allows you to create new classes based on existing classes. It promotes code reuse, modularity, and extensibility.

## Base (Parent) Class

A base (parent) class is the class that is inherited from. It defines common attributes and methods that can be reused by other classes.

## Derived (Child) Class

A derived (child) class inherits attributes and methods from the base class. It can have additional attributes and methods of its own.

## Extending a Class

Extending a class means adding new functionality to a derived class. This can include overriding or extending methods inherited from the base class.

## Code Reusability

Inheritance promotes code reusability by allowing common functionalities to be defined in the base class and inherited by multiple child classes.

## Types of Inheritance

- Single Inheritance: A child class inherits from a single base class.
- Multiple Inheritance: A child class inherits from multiple base classes.

## Method Overriding

Method overriding allows a child class to provide a specific implementation for a method inherited from the parent class, enhancing flexibility in class design.

In the following code examples, we'll explore various aspects of inheritance, including method overriding and its practical applications.

In [ ]:
# Base Class
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        pass

# Derived Classes
class Dog(Animal):
    def speak(self):
        return f"{self.name} barks!"

class Cat(Animal):
    def speak(self):
        return f"{self.name} meows!"

# Create objects
dog = Dog("Buddy")
cat = Cat("Whiskers")

# Method Overriding
print(dog.speak())  # Calls the Dog class's speak method
print(cat.speak())  # Calls the Cat class's speak method

# Practical Application - Shapes
class Shape:
    def area(self):
        pass

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 * self.radius * self.radius

# Calculate areas
rectangle = Rectangle(4, 5)
circle = Circle(3)
print("Rectangle Area:", rectangle.area())
print("Circle Area:", circle.area())

In [ ]:
## Defining lists to populate dictionary
filenames = ["Beagle_01141.jpg", "Beagle_01125.jpg", "skunk_029.jpg" ]
pet_labels = ["beagle", "beagle", "skunk"]
classifier_labels = ["walker hound, walker foxhound", "beagle",
                     "skunk, polecat, wood pussy"]
pet_label_is_dog = [1, 1, 0]
classifier_label_is_dog = [1, 1, 0]

## Defining empty dictionary
results_dic = dict()

## Populates empty dictionary with both labels &indicates if they match (idx 2)
for idx in range (0, len(filenames), 1):
    # If first time key is assigned initialize the list with pet &
    # classifier labels
    if filenames[idx] not in results_dic:
        results_dic[filenames[idx]] = [ pet_labels[idx], classifier_labels[idx] ]

    # Determine if pet_labels matches classifier_labels using in operator
    # - so if pet label is 'in' classifier label it's a match
    # ALSO since Key already exists because labels were added, append
    # value to end of list for idx 2
    # if pet image label was FOUND then there is a match
    if pet_labels[idx] in classifier_labels[idx]:
        results_dic[filenames[idx]].append(1)

    # if pet image label was NOT found then there is no match
    else:
        results_dic[filenames[idx]].append(0)

## Populates dictionary with whether or not labels indicate a dog image (idx 3&4)
for idx in range (0, len(filenames), 1):
    # Key already exists, extend values to end of list for idx 3 & 4
    results_dic[filenames[idx]].extend([pet_label_is_dog[idx],
                                       classifier_label_is_dog[idx]])

## Iterates through the list to print the results for each filename
for key in results_dic:
    print("\nFilename=", key, "\npet_image Label=", results_dic[key][0],
          "\nClassifier Label=", results_dic[key][1], "\nmatch=",
          results_dic[key][2], "\nImage is dog=", results_dic[key][3],
          "\nClassifier is dog=", results_dic[key][4])

    # Provides classifications of the results
    if sum(results_dic[key][2:]) == 3:
        print("*Breed Match*")
    if sum(results_dic[key][3:]) == 2:
        print("*Is-a-Dog Match*")
    if sum(results_dic[key][3:]) == 0 and results_dic[key][2] == 1:
        print("*NOT-a-Dog Match*")

Filename= Beagle_01141.jpg
pet_image Label= beagle
Classifier Label= walker hound, walker foxhound
match= 0
Image is dog= 1
Classifier is dog= 1
*Is-a-Dog Match*

Filename= Beagle_01125.jpg
pet_image Label= beagle
Classifier Label= beagle
match= 1
Image is dog= 1
Classifier is dog= 1
*Breed Match*
*Is-a-Dog Match*

Filename= skunk_029.jpg
pet_image Label= skunk
Classifier Label= skunk, polecat, wood pussy
match= 1
Image is dog= 0
Classifier is dog= 0
*NOT-a-Dog Match*

# Python Decorators

## Introduction

In Python, decorators are a powerful and flexible way to modify the behavior of functions or methods. Decorators allow you to wrap another function or method and perform actions before, after, or around the original function without modifying its code directly.

## Basics of Decorators

### What is a Decorator?

A decorator is a function that takes another function (or method) as input and extends or modifies its behavior. Decorators are denoted using the `@decorator` syntax in Python.

### Syntax

```python
@decorator
def my_function():
    # function implementation
```

### Example - Simple Decorator

```python
def simple_decorator(func):
    def wrapper():
        print("Something is happening before the function is called.")
        func()
        print("Something is happening after the function is called.")
    return wrapper

@simple_decorator
def say_hello():
    print("Hello!")

say_hello()
```

In this example, `simple_decorator` is a decorator that wraps the `say_hello` function. When `say_hello` is called, the additional actions defined in `simple_decorator` are executed.

## Decorators with Parameters

Decorators can also accept parameters, allowing for more flexibility.

### Example - Decorator with Parameter

```python
def parametrized_decorator(prefix):
    def decorator(func):
        def wrapper():
            print(f"{prefix}: Something is happening before the function is called.")
            func()
            print(f"{prefix}: Something is happening after the function is called.")
        return wrapper
    return decorator

@parametrized_decorator("LOG")
def say_hello():
    print("Hello!")

say_hello()
```

In this example, `parametrized_decorator` is a decorator that takes a parameter (`prefix`). The returned decorator (`decorator`) then wraps the target function.

## Use Cases of Decorators

### Logging Example

In [ ]:
def log_function_call(func):
    def wrapper(*args, **kwargs):
        print(f"Calling {func.__name__} with arguments {args} and keyword arguments {kwargs}")
        result = func(*args, **kwargs)
        print(f"{func.__name__} returned {result}")
        return result
    return wrapper

@log_function_call
def add(a, b):
    return a + b

result = add(3, 5)

In this example, the `log_function_call` decorator logs the function call details, making it useful for debugging and monitoring.

### Timing Example

In [ ]:
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"{func.__name__} took {end_time - start_time:.2f} seconds to execute.")
        return result
    return wrapper

@timing_decorator
def time_consuming_function():
    # Simulate a time-consuming operation
    time.sleep(2)
    print("Function execution complete.")

time_consuming_function()

Here, the `timing_decorator` measures the execution time of the wrapped function.

# References

1. Asgharpoor, A. (Fall 2023). "Programming Essentials" Course.

2. Python Official Documentation. Retrieved from [https://www.python.org/doc/](https://www.python.org/doc/)

3. GitHub Documentation. Retrieved from [https://docs.github.com/en](https://docs.github.com/en)

4. Kaggle Documentation. Retrieved from [https://www.kaggle.com/docs](https://www.kaggle.com/docs)

5. Jupyter Documentation. Retrieved from [https://jupyter-notebook.readthedocs.io/](https://jupyter-notebook.readthedocs.io/)

6. Real Python. (n.d.). "Python Basics: A Practical Introduction to Python 3." Retrieved from [https://realpython.com/python-basics/](https://realpython.com/python-basics/)

7. W3Schools. (n.d.). "Python Tutorial." Retrieved from [https://www.w3schools.com/python/](https://www.w3schools.com/python/)

8. Stack Overflow. (n.d.). [https://stackoverflow.com/](https://stackoverflow.com/)

9. VanderPlas, J. (2016). "Python Data Science Handbook." O'Reilly Media.

10. McKinney, W. (2017). "Python for Data Analysis." O'Reilly Media.

11. Downey, A. (2015). "Think Python: How to Think Like a Computer Scientist." O'Reilly Media.

12. Python Software Foundation. (n.d.). "The Python Standard Library." Retrieved from [https://docs.python.org/3/library/](https://docs.python.org/3/library/)

13. Conda Documentation. Retrieved from [https://docs.conda.io/](https://docs.conda.io/)

14. Real Python. (n.d.). "Python IDEs and Code Editors (Guide)." Retrieved from [https://realpython.com/python-ides-code-editors-guide/](https://realpython.com/python-ides-code-editors-guide/)

15. Real Python. (n.d.). "Python Virtual Environments: A Primer." Retrieved from [https://realpython.com/python-virtual-environments-a-primer/](https://realpython.com/python-virtual-environments-a-primer/)

16. Visual Studio Code Documentation. Retrieved from [https://code.visualstudio.com/docs](https://code.visualstudio.com/docs)

17. Images: https://www.freepik.com/

---
## Contact Information

- **Email:** A.Asgharpoor1993@Gmail.com
- **Portfolio:** [ArmanAsq.GitHub.io](https://ArmanAsq.GitHub.io)
- **GitHub Profile:** [github.com/armanasq](https://github.com/armanasq)